### ISSUE TITLE
The license is confusing

### ISSUE THREAD

**Issue by PurplePenguin4102** [CaptainAchilles/crispy-charts#1]
I found your licensing rules confusing, do I have to attribute and then state my modifications? Or can I just attribute and then sell the resulting product without stating modifications explicitly.

Also I'd suggest using more agendered terms in your terms and conditions

**Comment by CaptainAchilles** [comment]
Hey @PurplePenguin4102 (Nice name by the way 🥇 )
Thanks for your interest in this project!

It is very refreshing to read that you are taking licensing seriously. There seems to be an ever prevalent ingrained culture in my social circles which have a blatant disrespect for the wishes of hard working software authors. 

I can understand your confusion with the MIT license; even though it is intended to be simple and easy to follow, the wording gets quite verbose and complicated at times. Having read through the license with gender neutrality in mind, I have decided that it is important to not restrict its use to just people, but rather to avow permission to all. (See: ca933a38f86bd5c407964dba7fc0be8b70089e0a)

Secondly, to address your confusion about the license, I will put it this way: You do not have to attribute, but just redistribute the MIT license associated with any code from this repository.
